# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  omniauth_provider_key: <%= Figaro.env.omniauth_provider_key %>
  omniauth_provider_secret: <%= Figaro.env.omniauth_provider_secret %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  mail_password: <%= Figaro.env.mail_password %>
  mailchimp_api_key: <%= Figaro.env.mailchimp_api_key %>
  mailchimp_list_id: <%= Figaro.env.mailchimp_list_id %>
  btcscript_admin_uid: <%= Figaro.env.btcscript_admin_uid %>
  access_key_id: <%= Figaro.env.access_key_id %>
  secret_access_key: <%= Figaro.env.secret_access_key %>

test:
  secret_key_base: 962b237094f44fc88deaf6f2609f6fd20afb2b18561531b7d142725a15fb2a6fa31593eb0542d49114949ffb14eae5e60bfe32f923a83c9eb387be83e6e9c6e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  omniauth_provider_key: <%= Figaro.env.omniauth_provider_key %>
  omniauth_provider_secret: <%= Figaro.env.omniauth_provider_secret %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  mail_password: <%= Figaro.env.mail_password %>
  mailchimp_api_key: <%= Figaro.env.mailchimp_api_key %>
  mailchimp_list_id: <%= Figaro.env.mailchimp_list_id %>
  btcscript_admin_uid: <%= Figaro.env.btcscript_admin_uid %>
  access_key_id: <%= Figaro.env.access_key_id %>
  secret_access_key: <%= Figaro.env.secret_access_key %>